$("#e1").select2({
placeholder: "Select your UG University",
data:[
{ id:0  , text:"Acharya N.G. Ranga Agricultural University"},
{ id:1  , text:"Acharya Nagarjuna University"},
{ id:2  , text:"Adikavi Nannaya University"},
{ id:3  , text:"Ahmedabad University"},
{ id:4  , text:"Alagappa University"},
{ id:5  , text:"Aliah University"},
{ id:6  , text:"Aligarh Muslim University"},
{ id:7  , text:"All India Institute of Medical Sciences"},
{ id:8  , text:"Alliance University"},
{ id:9  , text:"Amity University"},
{ id:10 , text:"Amrita Vishwa Vidyapeetham"},
{ id:11 , text:"Anand Agricultural University"},
{ id:12 , text:"Andhra University"},
{ id:13 , text:"Anna University"},
{ id:14 , text:"Annamalai University"},
{ id:15 , text:"Apeejay Stya University"},
{ id:16 , text:"Arni University"},
{ id:17 , text:"Aryabhatta Knowledge University"},
{ id:18 , text:"Assam Agricultural University"},
{ id:19 , text:"Assam Don Bosco University"},
{ id:20 , text:"Assam University"},
{ id:21 , text:"Avinashilingam University"},
{ id:22 , text:"Awadhesh Pratap Singh University"},
{ id:23 , text:"Ayush and Health Sciences University of Chhattisgarh"},
{ id:24 , text:"Azim Premji University"},
{ id:25 , text:"B.R. Ambedkar Bihar University"},
{ id:26 , text:"B.S. Abdur Rahman University"},
{ id:27 , text:"Baba Farid University of Health Sciences"},
{ id:28 , text:"Baba Ghulam Shah Badhshah University"},
{ id:29 , text:"Babasaheb Bhimrao Ambedkar University"},
{ id:30 , text:"Babu Banarasi Das University"},
{ id:31 , text:"Baddi University of Emerging Sciences and Technologies"},
{ id:32 , text:"BAHRA University"},
{ id:33 , text:"Banaras Hindu University"},
{ id:34 , text:"Banasthali Vidyapith"},
{ id:35 , text:"Bangalore University"},
{ id:36 , text:"Barkatullah University"},
{ id:37 , text:"Bastar Vishwavidyalaya"},
{ id:38 , text:"Bengal Engineering and Science University"},
{ id:39 , text:"Berhampur University"},
{ id:40 , text:"Bhagat Phool Singh Mahila Vishwavidyalaya"},
{ id:41 , text:"Bhagwant University"},
{ id:42 , text:"Bharat Ratna Dr. B.R. Ambedkar University"},
{ id:43 , text:"Bharathiar University"},
{ id:44 , text:"Bharathidasan University"},
{ id:45 , text:"Bharati Vidyapeeth University"},
{ id:46 , text:"Bhatkhande Music Institute"},
{ id:47 , text:"Bhupendra Narayan Mandal University"},
{ id:48 , text:"Bidhan Chandra Krishi Vishwavidyalaya"},
{ id:49 , text:"Biju Patnaik University of Technology, Orissa"},
{ id:50 , text:"Birla Institute of Technology"},
{ id:51 , text:"Birla Institute of Technology and Science"},
{ id:52 , text:"Birsa Agricultural University"},
{ id:53 , text:"Bundelkhand University"},
{ id:54 , text:"Calorx Teachers' University"},
{ id:55 , text:"Central Agricultural University"},
{ id:56 , text:"Central Institute of Fisheries Education"},
{ id:57 , text:"Central University of Bihar"},
{ id:58 , text:"Central University of Gujarat"},
{ id:59 , text:"Central University of Haryana"},
{ id:60 , text:"Central University of Himachal Pradesh"},
{ id:61 , text:"Central University of Jharkhand"},
{ id:62 , text:"Central University of Karnataka"},
{ id:63 , text:"Central University of Kashmir"},
{ id:64 , text:"Central University of Kerala"},
{ id:65 , text:"Central University of Orissa"},
{ id:66 , text:"Central University of Punjab"},
{ id:67 , text:"Central University of Rajasthan"},
{ id:68 , text:"Central University of Tamil Nadu"},
{ id:69 , text:"Central University of Tibetan Studies"},
{ id:70 , text:"Centurion University of Technology and Management"},
{ id:71 , text:"CEPT University"},
{ id:72 , text:"Chanakya National Law University"},
{ id:73 , text:"Chandra Shekhar Azad University of Agriculture & Technology"},
{ id:74 , text:"Charotar University of Science & Technology"},
{ id:75 , text:"Chaudhary Charan Singh Haryana Agricultural University"},
{ id:76 , text:"Chaudhary Charan Singh University"},
{ id:77 , text:"Chaudhary Devi Lal University"},
{ id:78 , text:"Chennai Mathematical Institute"},
{ id:79 , text:"Chhatrapati Shahuji Maharaj Medical University"},
{ id:80 , text:"Chhatrapati Shahuji Maharaj University"},
{ id:81 , text:"Chhattisgarh Swami Vivekananda Technical University"},
{ id:82 , text:"Chitkara University"},
{ id:83 , text:"Cochin University of Science and Technology"},
{ id:84 , text:"CSK Himachal Pradesh Agricultural University"},
{ id:85 , text:"Damodaram Sanjivayya National Law University"},
{ id:86 , text:"Datta Meghe Institute of Medical Sciences"},
{ id:87 , text:"Davangere University"},
{ id:88 , text:"Dayalbagh Educational Institute"},
{ id:89 , text:"Deccan College Post-Graduate and Research Institute"},
{ id:90 , text:"Deen Dayal Upadhyay Gorakhpur University"},
{ id:91 , text:"Deenbandhu Chhotu Ram University of Science and Technology"},
{ id:92 , text:"Delhi Technological University"},
{ id:93 , text:"Delhi Technological University"},
{ id:94 , text:"Dev Sanskriti Vishwavidyalaya"},
{ id:95 , text:"Devi Ahilya Vishwavidyalaya"},
{ id:96 , text:"Dharmsinh Desai University"},
{ id:97 , text:"Dhirubhai Ambani Institute of Information & Communication Technology"},
{ id:98 , text:"Dibrugarh University"},
{ id:99 , text:"Doon University"},
{ id:100, text:"Dr K.N. Modi University"},
{ id:101, text:"Dr. B R Ambedkar National Institute of Technology Jalandhar"},
{ id:102, text:"Dr. B.R. Ambedkar University"},
{ id:103, text:"Dr. B.R. Ambedkar University"},
{ id:104, text:"Dr. Babasaheb Ambedkar Marathwada University"},
{ id:105, text:"Dr. Babasaheb Ambedkar Technological University"},
{ id:106, text:"Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth"},
{ id:107, text:"Dr. C.V. Raman University"},
{ id:108, text:"Dr. Hari Singh Gour University"},
{ id:109, text:"Dr. Panjabrao Deshmukh Krishi Vidyapeeth"},
{ id:110, text:"Dr. Ram Manohar Lohia Avadh University"},
{ id:111, text:"Dr. Ram Manohar Lohiya National Law University"},
{ id:112, text:"Dr. Shakuntala Misra Rehabilitation University"},
{ id:113, text:"Dr. Y.S. Parmar University of Horticulture and Forestry"},
{ id:114, text:"Dravidian University"},
{ id:115, text:"EIILM University"},
{ id:116, text:"Eternal University"},
{ id:117, text:"Fakir Mohan University"},
{ id:118, text:"Forest Research Institute"},
{ id:119, text:"Galgotias University"},
{ id:120, text:"Gandhi Institute of Technology and Management"},
{ id:121, text:"Gandhigram Rural University"},
{ id:122, text:"Ganpat University"},
{ id:123, text:"Gauhati University"},
{ id:124, text:"Gautam Buddha University"},
{ id:125, text:"GLA University"},
{ id:126, text:"Goa University"},
{ id:127, text:"Gokhale Institute of Politics and Economics"},
{ id:128, text:"Govind Ballabh Pant University of Agriculture & Technology"},
{ id:129, text:"Gujarat Ayurved University"},
{ id:130, text:"Gujarat Forensic Sciences University"},
{ id:131, text:"Gujarat National Law University"},
{ id:132, text:"Gujarat Technological University"},
{ id:133, text:"Gujarat University"},
{ id:134, text:"Gujarat Vidyapith"},
{ id:135, text:"Gulbarga University"},
{ id:136, text:"Guru Angad Dev Veterinary and Animal Sciences University"},
{ id:137, text:"Guru Ghasidas Vishwavidyalaya"},
{ id:138, text:"Guru Gobind Singh Indraprastha University"},
{ id:139, text:"Guru Jambheshwar University of Science & Technology"},
{ id:140, text:"Guru Nanak Dev University"},
{ id:141, text:"Hemchandracharya North Gujarat University"},
{ id:142, text:"Hemwati Nandan Bahuguna Garhwal University"},
{ id:143, text:"Hidayatullah National Law University"},
{ id:144, text:"Himachal Pradesh University"},
{ id:145, text:"Himgiri ZEE University"},
{ id:146, text:"Hindustan University"},
{ id:147, text:"Homi Bhabha National Institute"},
{ id:148, text:"ICFAI University, Dehradun"},
{ id:149, text:"ICFAI University, Jharkhand"},
{ id:150, text:"ICFAI University, Tripura"},
{ id:151, text:"IFHE Hyderabad"},
{ id:152, text:"IFTM University"},
{ id:153, text:"Indian Agricultural Research Institute"},
{ id:154, text:"Indian Institute of Foreign Trade"},
{ id:155, text:"Indian Institute of Information Technology Allahabad"},
{ id:156, text:"Indian Institute of Information Technology and Management Gwalior"},
{ id:157, text:"Indian Institute of Information Technology, Design and Manufacturing"},
{ id:158, text:"Indian Institute of Science"},
{ id:159, text:"Indian Institute of Space Science and Technology"},
{ id:160, text:"Indian Institute of Technology Bhubaneswar"},
{ id:161, text:"Indian Institute of Technology Bombay"},
{ id:162, text:"Indian Institute of Technology Delhi"},
{ id:163, text:"Indian Institute of Technology Gandhinagar"},
{ id:164, text:"Indian Institute of Technology Guwahati"},
{ id:165, text:"Indian Institute of Technology Hyderabad"},
{ id:166, text:"Indian Institute of Technology Indore"},
{ id:167, text:"Indian Institute of Technology Jodhpur"},
{ id:168, text:"Indian Institute of Technology Kanpur"},
{ id:169, text:"Indian Institute of Technology Kharagpur"},
{ id:170, text:"Indian Institute of Technology Madras"},
{ id:171, text:"Indian Institute of Technology Mandi"},
{ id:172, text:"Indian Institute of Technology Patna"},
{ id:173, text:"Indian Institute of Technology Roorkee"},
{ id:174, text:"Indian Institute of Technology Ropar"},
{ id:175, text:"Indian Maritime University"},
{ id:176, text:"Indian School of Mines"},
{ id:177, text:"Indian Statistical Institute"},
{ id:178, text:"Indian Veterinary Research Institute"},
{ id:179, text:"Indira Gandhi Agricultural University"},
{ id:180, text:"Indira Gandhi Institute of Development Research"},
{ id:181, text:"Indira Gandhi National Tribal University"},
{ id:182, text:"Indira Kala Sangit Vishwavidyalaya"},
{ id:183, text:"Indraprastha Institute of Information Technology"},
{ id:184, text:"Indus International University"},
{ id:185, text:"Institute of Chemical Technology"},
{ id:186, text:"Integral University"},
{ id:187, text:"International Institute for Population Sciences"},
{ id:188, text:"International Institute of Information Technology Bangalore"},
{ id:189, text:"International Institute of Information Technology, Hyderabad"},
{ id:190, text:"Invertis University"},
{ id:191, text:"Islamic University of Science and Technology"},
{ id:192, text:"ITM University"},
{ id:193, text:"Jadavpur University"},
{ id:194, text:"Jagadguru Ramanandacharya Rajasthan Sanskrit University"},
{ id:195, text:"Jagan Nath University"},
{ id:196, text:"Jagdishprasad Jhabarmal Tibrewala University"},
{ id:197, text:"Jai Narain Vyas University"},
{ id:198, text:"Jai Prakash Vishwavidyalaya"},
{ id:199, text:"Jain Vishva Bharati University"},
{ id:200, text:"Jaipur National University"},
{ id:201, text:"Jamia Hamdard"},
{ id:202, text:"Jamia Millia Islamia"},
{ id:203, text:"Jawaharlal Institute of Postgraduate Medical Education & Research"},
{ id:204, text:"Jawaharlal Nehru Architecture and Fine Arts University"},
{ id:205, text:"Jawaharlal Nehru Centre for Advanced Scientific Research"},
{ id:206, text:"Jawaharlal Nehru Krishi Vishwavidyalaya"},
{ id:207, text:"Jawaharlal Nehru Technological University"},
{ id:208, text:"Jawaharlal Nehru Technological University, Anantapur"},
{ id:209, text:"Jawaharlal Nehru Technological University, Kakinada"},
{ id:210, text:"Jawaharlal Nehru University"},
{ id:211, text:"Jayoti Vidyapeeth Women's University"},
{ id:212, text:"Jaypee University of Engineering & Technology"},
{ id:213, text:"Jaypee University of Information Technology"},
{ id:214, text:"Jiwaji University"},
{ id:215, text:"Jodhpur National University"},
{ id:216, text:"JSS University"},
{ id:217, text:"Junagadh Agricultural University"},
{ id:218, text:"K L University"},
{ id:219, text:"Kadi Sarva VishwaVidyalaya"},
{ id:220, text:"Kakatiya University"},
{ id:221, text:"Kameshwar Singh Darbhanga Sanskrit University"},
{ id:222, text:"Kannada University"},
{ id:223, text:"Kannur University"},
{ id:224, text:"Karnatak University"},
{ id:225, text:"Karnataka State Law University"},
{ id:226, text:"Karnataka State Women's University"},
{ id:227, text:"Karnataka Veterinary, Animal and Fisheries Sciences University"},
{ id:228, text:"Karunya University"},
{ id:229, text:"Kavikulguru Kalidas Sanskrit University"},
{ id:230, text:"Kerala Agricultural University"},
{ id:231, text:"Kerala Kalamandalam"},
{ id:232, text:"Kerala University of Fisheries and Ocean Studies"},
{ id:233, text:"Kerala University of Health Sciences"},
{ id:234, text:"Kerala Veterinary and Animal Sciences University"},
{ id:235, text:"KIIT University"},
{ id:236, text:"KLE University"},
{ id:237, text:"Kolhan University"},
{ id:238, text:"Krantiguru Shyamji Krishna Verma Kachchh University"},
{ id:239, text:"Krishna University"},
{ id:240, text:"Kumaun University"},
{ id:241, text:"Kurukshetra University"},
{ id:242, text:"Kushabhau Thakre Patrakarita Avam Jansanchar University"},
{ id:243, text:"Kuvempu University"},
{ id:244, text:"Lakshmibai National Institute of Physical Education"},
{ id:245, text:"Lalit Narayan Mithila University"},
{ id:246, text:"Lovely Professional University"},
{ id:247, text:"Madhya Pradesh Pashu-Chikitsa Vigyan Vishwavidyalaya"},
{ id:248, text:"Madurai Kamaraj University"},
{ id:249, text:"Magadh University"},
{ id:250, text:"Mahamaya Technical University"},
{ id:251, text:"Maharaja Ganga Singh University"},
{ id:252, text:"Maharaja Krishnakumarsinhji Bhavnagar University"},
{ id:253, text:"Maharana Pratap University of Agriculture and Technology"},
{ id:254, text:"Maharashtra Animal and Fishery Sciences University"},
{ id:255, text:"Maharashtra University of Health Sciences"},
{ id:256, text:"Maharishi Dayanand University"},
{ id:257, text:"Maharishi Mahesh Yogi Vedic Vishwavidyalaya"},
{ id:258, text:"Maharishi Panini Sanskrit Vishwavidyalaya"},
{ id:259, text:"Maharishi University of Management and Technology"},
{ id:260, text:"Maharshi Dayanand Saraswati University"},
{ id:261, text:"Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya"},
{ id:262, text:"Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya"},
{ id:263, text:"Mahatma Gandhi Kashi Vidyapeeth"},
{ id:264, text:"Mahatma Gandhi University"},
{ id:265, text:"Mahatma Gandhi University"},
{ id:266, text:"Mahatma Gandhi University"},
{ id:267, text:"Mahatma Jyoti Rao Phoole University"},
{ id:268, text:"Mahatma Jyotiba Phule Rohilkhand University"},
{ id:269, text:"Mahatma Phule Krishi Vidyapeeth"},
{ id:270, text:"Makhanlal Chaturvedi Rashtriya Patrakarita Vishwavidyalaya"},
{ id:271, text:"Malaviya National Institute of Technology, Jaipur"},
{ id:272, text:"Manav Bharti University"},
{ id:273, text:"Mangalayatan University"},
{ id:274, text:"Mangalore University"},
{ id:275, text:"Manipal University"},
{ id:276, text:"Manipur University"},
{ id:277, text:"Manonmaniam Sundaranar University"},
{ id:278, text:"Marathwada Agricultural University"},
{ id:279, text:"Martin Luther Christian University"},
{ id:280, text:"MATS University"},
{ id:281, text:"Maulana Azad National Institute of Technology"},
{ id:282, text:"Maulana Azad National Urdu University"},
{ id:283, text:"Maulana Mazharul Haque Arabic and Persian University"},
{ id:284, text:"Mewar University"},
{ id:285, text:"MGM Institute of Health Sciences"},
{ id:286, text:"Mizoram University"},
{ id:287, text:"Mohammad Ali Jauhar University"},
{ id:288, text:"Mohanlal Sukhadia University"},
{ id:289, text:"Mother Teresa Women's University"},
{ id:290, text:"Motilal Nehru National Institute of Technology"},
{ id:291, text:"Nagaland University"},
{ id:292, text:"NALSAR University of Law"},
{ id:293, text:"Narendra Dev University of Agriculture and Technology"},
{ id:294, text:"Narsee Monjee Institute of Management and Higher Studies"},
{ id:295, text:"National Dairy Research Institute"},
{ id:296, text:"National Institute of Design"},
{ id:297, text:"National Institute of Fashion Technology"},
{ id:298, text:"National Institute of Mental Health and Neuro Sciences"},
{ id:299, text:"National Institute of Pharmaceutical Education and Research"},
{ id:300, text:"National Institute of Pharmaceutical Education and Research, Ahmedabad"},
{ id:301, text:"National Institute of Pharmaceutical Education and Research, Guwahati"},
{ id:302, text:"National Institute of Pharmaceutical Education and Research, Hajipur"},
{ id:303, text:"National Institute of Pharmaceutical Education and Research, Hyderabad"},
{ id:304, text:"National Institute of Pharmaceutical Education and Research, Kolkata"},
{ id:305, text:"National Institute of Pharmaceutical Education and Research, Rae Bareli"},
{ id:306, text:"National Institute of Technology Calicut"},
{ id:307, text:"National Institute of Technology Karnataka"},
{ id:308, text:"National Institute of Technology Raipur"},
{ id:309, text:"National Institute of Technology, Agartala"},
{ id:310, text:"National Institute of Technology, Durgapur"},
{ id:311, text:"National Institute of Technology, Hamirpur"},
{ id:312, text:"National Institute of Technology, Jamshedpur"},
{ id:313, text:"National Institute of Technology, Kurukshetra"},
{ id:314, text:"National Institute of Technology, Patna"},
{ id:315, text:"National Institute of Technology, Rourkela"},
{ id:316, text:"National Institute of Technology, Silchar"},
{ id:317, text:"National Institute of Technology, Srinagar"},
{ id:318, text:"National Institute of Technology, Tiruchirappalli"},
{ id:319, text:"National Institute of Technology, Warangal"},
{ id:320, text:"National Law Institute University"},
{ id:321, text:"National Law School of India University"},
{ id:322, text:"National Law University"},
{ id:323, text:"National Law University, Jodhpur"},
{ id:324, text:"National Law University, Orissa"},
{ id:325, text:"National University of Educational Planning and Administration"},
{ id:326, text:"National University of Study and Research in Law"},
{ id:327, text:"Navsari Agricultural University"},
{ id:328, text:"Netaji Subhas Institute of Technology"},
{ id:329, text:"Nilamber-Pitamber University"},
{ id:330, text:"NIMS University"},
{ id:331, text:"Nirma University of Science and Technology"},
{ id:332, text:"NITTE University"},
{ id:333, text:"Nizam's Institute of Medical Sciences"},
{ id:334, text:"Noida International University"},
{ id:335, text:"North Eastern Hill University"},
{ id:336, text:"North Eastern Regional Institute of Science and Technology"},
{ id:337, text:"North Maharashtra University"},
{ id:338, text:"North Orissa University"},
{ id:339, text:"NTR University of Health Sciences"},
{ id:340, text:"O.P. Jindal Global University"},
{ id:341, text:"Orissa University of Agriculture and Technology"},
{ id:342, text:"Osmania University"},
{ id:343, text:"Pacific University"},
{ id:344, text:"Padmashree Dr. D.Y. Patil Vidyapith"},
{ id:345, text:"Palamuru University"},
{ id:346, text:"Pandit Deendayal Petroleum University"},
{ id:347, text:"Pandit Ravishankar Shukla University"},
{ id:348, text:"Panjab University"},
{ id:349, text:"Patna University"},
{ id:350, text:"PDPM Indian Institute of Information Technology, Design & Manufacturing"},
{ id:351, text:"PEC University of Technology"},
{ id:352, text:"Periyar Maniammai University"},
{ id:353, text:"Pondicherry University"},
{ id:354, text:"Post Graduate Institute of Medical Education and Research"},
{ id:355, text:"Potti Sreeramulu Telugu University"},
{ id:356, text:"Pravara Institute of Medical Sciences"},
{ id:357, text:"Presidency University"},
{ id:358, text:"Pt. B. D. Sharma University of Health Sciences"},
{ id:359, text:"Punjab Agricultural University"},
{ id:360, text:"Punjab Technical University"},
{ id:361, text:"Punjabi University"},
{ id:362, text:"Rabindra Bharati University"},
{ id:363, text:"Raffles University"},
{ id:364, text:"Rajasthan Agricultural University"},
{ id:365, text:"Rajasthan Ayurved University"},
{ id:366, text:"Rajasthan Technical University Kota"},
{ id:367, text:"Rajasthan University of Health Sciences"},
{ id:368, text:"Rajendra Agricultural University"},
{ id:369, text:"Rajiv Gandhi National University of Law"},
{ id:370, text:"Rajiv Gandhi Proudyogiki Vishwavidyalaya"},
{ id:371, text:"Rajiv Gandhi University"},
{ id:372, text:"Rajiv Gandhi University of Health Sciences"},
{ id:373, text:"Ramakrishna Mission Vivekananda University"},
{ id:374, text:"Ranchi University"},
{ id:375, text:"Rani Channamma University"},
{ id:376, text:"Rani Durgavati Vishwavidyalaya"},
{ id:377, text:"Rashtrasant Tukadoji Maharaj Nagpur University"},
{ id:378, text:"Rashtriya Sanskrit Sansthan"},
{ id:379, text:"Rashtriya Sanskrit Vidyapeetha"},
{ id:380, text:"Ravenshaw University"},
{ id:381, text:"Rayalaseema University"},
{ id:382, text:"Sam Higginbottom Institute of Agriculture, Technology and Sciences"},
{ id:383, text:"Sambalpur University"},
{ id:384, text:"Sampurnanand Sanskrit Vishvavidyalaya"},
{ id:385, text:"Sanjay Gandhi Post Graduate Institute of Medical Sciences"},
{ id:386, text:"Sant Gadge Baba Amravati University"},
{ id:387, text:"Sant Longowal Institute of Engineering and Technology"},
{ id:388, text:"Sardar Patel University"},
{ id:389, text:"Sardar Vallabhbhai National Institute of Technology, Surat"},
{ id:390, text:"Sardar Vallabhbhai Patel University of Agriculture and Technology"},
{ id:391, text:"Sardarkrushinagar Dantiwada Agricultural University"},
{ id:392, text:"Sarguja University"},
{ id:393, text:"SASTRA University"},
{ id:394, text:"Satavahana University"},
{ id:395, text:"Sathyabama University"},
{ id:396, text:"Saurashtra University"},
{ id:397, text:"School of Planning and Architecture, Delhi"},
{ id:398, text:"Sharda University"},
{ id:399, text:"Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir"},
{ id:400, text:"Shiv Nadar University"},
{ id:401, text:"Shivaji University"},
{ id:402, text:"Shoolini University of Biotechnology and Management Sciences"},
{ id:403, text:"Shree Somnath Sanskrit University"},
{ id:404, text:"Shreemati Nathibai Damodar Thackersey Women's University"},
{ id:405, text:"Shri Guru Ram Rai Education Mission"},
{ id:406, text:"Shri Jagannath Sanskrit Vishvavidyalaya"},
{ id:407, text:"Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha"},
{ id:408, text:"Shri Mata Vaishno Devi University"},
{ id:409, text:"Shri Venkateshwara University"},
{ id:410, text:"Shridhar University"},
{ id:411, text:"Sidho Kanho Birsha University"},
{ id:412, text:"Sido Kanhu Murmu University"},
{ id:413, text:"Sikkim Manipal University"},
{ id:414, text:"Sikkim University"},
{ id:415, text:"Singhania University"},
{ id:416, text:"Sir Padampat Singhania University"},
{ id:417, text:"South Asian University"},
{ id:418, text:"Sree Chitra Thirunal Institute of Medical Sciences and Technology"},
{ id:419, text:"Sree Sankaracharya University of Sanskrit"},
{ id:420, text:"Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya"},
{ id:421, text:"Sri Guru Granth Sahib World University"},
{ id:422, text:"Sri Krishnadevaraya University"},
{ id:423, text:"Sri Padmavati Mahila Visvavidyalayam"},
{ id:424, text:"Sri Ramachandra University"},
{ id:425, text:"Sri Sai University"},
{ id:426, text:"Sri Venkateswara Institute of Medical Sciences"},
{ id:427, text:"Sri Venkateswara University"},
{ id:428, text:"Sri Venkateswara Vedic University"},
{ id:429, text:"Sri Venkateswara Veterinary University"},
{ id:430, text:"SRM University"},
{ id:431, text:"Subharti University"},
{ id:432, text:"SunRise University"},
{ id:433, text:"Suresh Gyan Vihar University"},
{ id:434, text:"Swami Ramanand Teerth Marathwada University"},
{ id:435, text:"Symbiosis International University"},
{ id:436, text:"Tamil Nadu Agricultural University"},
{ id:437, text:"Tamil Nadu Dr Ambedkar Law University"},
{ id:438, text:"Tamil Nadu Dr. M.G.R.Medical University"},
{ id:439, text:"Tamil Nadu Physical Education and Sports University"},
{ id:440, text:"Tamil Nadu Teacher Education University"},
{ id:441, text:"Tamil Nadu Veterinary and Animal Sciences University"},
{ id:442, text:"Tamil University"},
{ id:443, text:"Tata Institute of Fundamental Research"},
{ id:444, text:"Tata Institute of Social Sciences"},
{ id:445, text:"Teerthanker Mahaveer University"},
{ id:446, text:"Telangana University"},
{ id:447, text:"TERI University"},
{ id:448, text:"Tezpur University"},
{ id:449, text:"Thapar University"},
{ id:450, text:"The English and Foreign Languages University"},
{ id:451, text:"The Indian Law Institute"},
{ id:452, text:"The LNM Institute of Information Technology"},
{ id:453, text:"The Maharaja Sayajirao University of Baroda"},
{ id:454, text:"The National University of Advanced Legal Studies"},
{ id:455, text:"The WB National University of Juridical Sciences"},
{ id:456, text:"Thiruvalluvar University"},
{ id:457, text:"Tilka Manjhi Bhagalpur University"},
{ id:458, text:"Tripura University"},
{ id:459, text:"Tumkur University"},
{ id:460, text:"University of Agricultural Sciences, Bangalore"},
{ id:461, text:"University of Agricultural Sciences, Dharwad"},
{ id:462, text:"University of Allahabad"},
{ id:463, text:"University of Burdwan"},
{ id:464, text:"University of Calcutta"},
{ id:465, text:"University of Calicut"},
{ id:466, text:"University of Delhi"},
{ id:467, text:"University of Gour Banga"},
{ id:468, text:"University of Hyderabad"},
{ id:469, text:"University of Jammu"},
{ id:470, text:"University of Kalyani"},
{ id:471, text:"University of Kashmir"},
{ id:472, text:"University of Kerala"},
{ id:473, text:"University of Kota"},
{ id:474, text:"University of Lucknow"},
{ id:475, text:"University of Madras"},
{ id:476, text:"University of Mumbai"},
{ id:477, text:"University of Mysore"},
{ id:478, text:"University of North Bengal"},
{ id:479, text:"University of Petroleum and Energy Studies"},
{ id:480, text:"University of Pune"},
{ id:481, text:"University of Rajasthan"},
{ id:482, text:"University of Science and Technology, Meghalaya"},
{ id:483, text:"University of Solapur"},
{ id:484, text:"University of Technology & Management"},
{ id:485, text:"Utkal University"},
{ id:486, text:"Utkal University of Culture"},
{ id:487, text:"Uttar Banga Krishi Viswavidyalaya"},
{ id:488, text:"Uttar Pradesh Technical University"},
{ id:489, text:"Uttarakhand Technical University"},
{ id:490, text:"Uttaranchal Sanskrit University"},
{ id:491, text:"Veer Bahadur Singh Purvanchal University"},
{ id:492, text:"Veer Narmad South Gujarat University"},
{ id:493, text:"Veer Surendra Sai University of Technology"},
{ id:494, text:"Vel Tech Dr.RR & Dr.SR Technical University"},
{ id:495, text:"Vidyasagar University"},
{ id:496, text:"Vijayanagara Sri Krishnadevaraya University"},
{ id:497, text:"Vikram University"},
{ id:498, text:"Vikrama Simhapuri University"},
{ id:499, text:"Vinayaka Missions Sikkim University"},
{ id:500, text:"Vinoba Bhave University"},
{ id:501, text:"Visva Bharati University"},
{ id:502, text:"Visvesvaraya National Institute of Technology"},
{ id:503, text:"Visvesvaraya Technological University"},
{ id:504, text:"VIT University"},
{ id:505, text:"West Bengal State University"},
{ id:506, text:"West Bengal University of Animal and Fishery Sciences"},
{ id:507, text:"West Bengal University of Health Sciences"},
{ id:508, text:"West Bengal University of Technology"},
{ id:509, text:"YMCA University of Science and Technology"},
{ id:510, text:"Yogi Vemana University"}]
}).on("select2-blur", 
		function(e)
		{
          if($('#e1').select2('val') == "")
         {
           document.getElementById("userUgUnivGroup").className="has-error";
           $error=false;
         }
         else{

            document.getElementById("userUgUnivGroup").className="has-success";
         }
      	});

